services:
  api:
    build: ./api
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - API_HOST=${API_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=mysql+mysqlconnector://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_INITDB_SKIP_TZ_DATABASE=true
      - MYSQL_INITDB_ARGS=--default-authentication-plugin=mysql_native_password
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./webapp_flutter
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api

volumes:
  db_data:
