"""empty message

Revision ID: 5a8c37ab29fb
Revises: 
Create Date: 2024-10-29 04:23:57.319318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8c37ab29fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=60), nullable=False),
    sa.Column('custo', sa.Numeric(precision=13, scale=3), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_loja',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=13, scale=3), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('id_loja', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_produto', 'id_loja', name='unique_produto_loja')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_loja')
    op.drop_table('produto')
    op.drop_table('loja')
    # ### end Alembic commands ###
